Repository S-nect1/matchday-fe, pull requests merged in 2025-08, with the labels that each got.

#11 [Chore] shadcn, tailwindcss, package.json 설정
  CONVENTION.md
  GEMINI.md
  GITHUB_COVENTION.md
  components.json
  index.html
  package-lock.json
  package.json
  reset.css
  src/app/App.tsx
  src/app/index.css
  src/app/main.tsx
  src/entities/example.ts
  src/features/example.ts
  src/pages/example.ts
  src/pages/home/index.ts
  src/pages/home/ui/HomePage.tsx
  src/shared/assets/match-day-logo.png
  src/shared/contexts/form-context.ts
  src/shared/hooks/use-form-field.ts
  src/shared/lib/button-variants.ts
  src/shared/lib/navigation-menu-trigger-style.ts
  src/shared/ui/Logo/Icon.tsx
  src/shared/ui/Logo/Text.tsx
  src/shared/ui/Logo/index.tsx
  src/shared/ui/avatar.tsx
  src/shared/ui/button.tsx
  src/shared/ui/card.tsx
  src/shared/ui/checkbox.tsx
  src/shared/ui/dropdown-menu.tsx
  src/shared/ui/form.tsx
  src/shared/ui/index.ts
  src/shared/ui/input.tsx
  src/shared/ui/label.tsx
  src/shared/ui/navigation-menu.tsx
  src/shared/ui/select.tsx
  src/shared/ui/separator.tsx
  src/shared/ui/tabs.tsx
  src/tailwind.colors.ts
  src/widgets/example.ts
  tailwind.config.js
  vite.config.ts
Labels: enhancement

#9 [AuthPage] 로그인/회원가입 페이지 구현 (추가정보 페이지 포함)
  src/app/router.tsx
  src/pages/index.ts
  src/pages/login/index.ts
  src/pages/login/ui/LoginPage.tsx
  src/pages/signup-additional-info-page/assets/avatar.png
  src/pages/signup-additional-info-page/index.tsx
  src/pages/signup-additional-info-page/ui/SignupAdditionalInfoPage/FormSection.tsx
  src/pages/signup-additional-info-page/ui/SignupAdditionalInfoPage/ProfileSection.tsx
  src/pages/signup-additional-info-page/ui/SignupAdditionalInfoPage/index.tsx
  src/pages/signup-form/index.ts
  src/pages/signup-form/ui/SignupFormPage.tsx
  src/pages/signup/assets/kakao-icon.svg
  src/pages/signup/index.ts
  src/pages/signup/ui/AdditionalInfoPage/AdditionalInfoPageFormSection.tsx
  src/pages/signup/ui/AdditionalInfoPage/AdditionalInfoPageProfileSection.tsx
  src/pages/signup/ui/AdditionalInfoPage/index.tsx
  src/pages/signup/ui/SignupPage.tsx
Labels: enhancement

#35 style: import 규칙 적용 (Organize Import 사용)
  src/app/layouts/HomeLayout.tsx
  src/app/layouts/MainLayout.tsx
  src/app/layouts/ui/MainBanner.tsx
  src/app/main.tsx
  src/app/router.tsx
  src/pages/create-match/ui/index.tsx
  src/pages/home/ui/FilterMatches/FilterMatchesAboutTeam.tsx
  src/pages/home/ui/GridViewCard.tsx
  src/pages/home/ui/ListViewCard.tsx
  src/pages/home/ui/index.tsx
  src/pages/login/ui/LoginPage.tsx
  src/shared/ui/index.ts
Labels: refactor

#37 feat: [TopImageBanner] 이미지 컴포넌트 구현
  src/app/layouts/ui/MainBanner.tsx
  src/shared/ui/index.ts
  src/shared/ui/page-banner/index.tsx
Labels: refactor

#31 feat: [Calendar] Calendar Component 구현
  src/shared/ui/calendar.tsx
  src/shared/ui/underline-tabs.tsx
Labels: enhancement

#39 chore: [Eslint] eslint import sorting 규칙 추가
  .gitignore
  .vscode/settings.json
  eslint.config.js
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/layouts/HomeLayout.tsx
  src/app/layouts/MainLayout.tsx
  src/app/main.tsx
  src/app/router.tsx
  src/features/form-input/ui/FormInput.tsx
  src/pages/create-match/ui/index.tsx
  src/pages/home/model/use-match-search-filters.ts
  src/pages/home/ui/FilterMatches/FilterMatchesAboutTeam.tsx
  src/pages/home/ui/FilterMatches/FilterMatchesLocationTime.tsx
  src/pages/home/ui/FilterMatches/FilterMatchesType.tsx
  src/pages/home/ui/FilterMatches/index.tsx
  src/pages/home/ui/GridViewCard.tsx
  src/pages/home/ui/ListViewCard.tsx
  src/pages/home/ui/index.tsx
  src/pages/login/index.ts
  src/pages/my-team/ui/MyTeamPage.tsx
  src/pages/my-team/ui/components/TeamInfoTab.tsx
  src/pages/signup-form/ui/SignupFormPage.tsx
  src/pages/signup/ui/SignupPage.tsx
  src/pages/team-form/ui/TeamForm.tsx
  src/pages/team-join/ui/TeamJoinPage.tsx
  src/pages/teams/ui/TeamsPage.tsx
  src/shared/contexts/form-context.ts
  src/shared/hooks/use-form-field.ts
  src/shared/hooks/use-my-team.ts
  src/shared/hooks/use-team-form.ts
  src/shared/lib/navigation-menu-trigger-style.ts
  src/shared/ui/Logo/Icon.tsx
  src/shared/ui/avatar.tsx
  src/shared/ui/badge.tsx
  src/shared/ui/checkbox.tsx
  src/shared/ui/color-picker.tsx
  src/shared/ui/dialog.tsx
  src/shared/ui/dropdown-menu.tsx
  src/shared/ui/form.tsx
  src/shared/ui/label.tsx
  src/shared/ui/navigation-menu.tsx
  src/shared/ui/separator.tsx
  src/shared/ui/tabs.tsx
  src/tailwind.colors.ts
  src/widgets/date-picker/ui/DatePicker.tsx
  src/widgets/filter-modal/ui/FilterModal.tsx
  src/widgets/footer/ui/Footer.tsx
  src/widgets/header/ui/Navigation.tsx
  src/widgets/location-map/ui/LocationMap.tsx
  src/widgets/navbar/ui/Navbar/BellIcon.tsx
  src/widgets/navbar/ui/Navbar/SearchIcon.tsx
  src/widgets/place-search-modal/ui/PlaceSearchModal.tsx
  src/widgets/tooltip/ui/CustomTooltip.tsx
Labels: chore

#48 chore: [Node ]20.16.0버전의 .nvmrc 파일 추가
  .nvmrc
  package-lock.json
Labels: chore

#60 refactor: [LocationMap, PlaceSearchModal] 최적화
  src/pages/create-match/model/use-create-match-form.ts
  src/pages/create-match/ui/index.tsx
  src/pages/create-match/ui/sections/MatchLocationSection.tsx
  src/widgets/location-map/ui/LocationMap.tsx
  src/widgets/place-search-modal/ui/MapSearchItem.tsx
  src/widgets/place-search-modal/ui/PlaceSearchModal.tsx
Labels: refactor
